# Generated by Django 4.2.3 on 2023-07-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
