# Generated by Django 4.2.3 on 2023-07-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTE', '0002_alter_book_image_alter_book_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
